version: 2

models:
  - name: reports
    description: |
      **Descrição**: View materializada integrando relatos de ocorrências a partir de diversas fontes: 1746, Disque Denúncia, Fogo Cruzado e Palver.
      **Frequência de atualização**: De acordo com as atualizações nas fontes
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@prefeitura.rio
    columns:
      - name: id_report
        description: "ID único nesta tabela concatenando id_source e id_report_original"
        data_tests:
          - unique

      - name: id_source
        description: "Fonte do relato"

      - name: id_report_original
        description: "ID do relato na tabela original"

      - name: data_report
        description: "Timestamp UTC do relato"

      - name: orgaos
        description: "Órgãos relacionados ao relato (presentes apenas nas fontes 1746 e Disque Denúncia)"

      - name: categoria
        description: "Categoria da fonte do relato"
        data_tests:
          - not_null

      - name: tipo_subtipo
        description: "Lista com tipos e subtipos de ocorrências presentes no relato"
        data_tests:
          - not_null

      - name: descricao
        description: "Texto completo do relato"
        data_tests:
          - not_null

      - name: logradouro
        description: "Rua ou Bairro da principal ocorrência do relato"

      - name: numero_logradouro
        description: "Número da localidade da principal ocorrência do relato"

      - name: latitude
        description: "Latitude da localidade da principal ocorrência do relato"

      - name: longitude
        description: "Longitude da localidade da principal ocorrência do relato"

      - name: updated_at
        description: "Timestamp UTC da inserção do registro na tabela"