version: 2

models:
  - name: denuncias
    description: |
      **Descrição**: Tabela que contém dados de denúncias, incluindo informações de localização e detalhes do relato.
      **Frequência de atualização**: A cada 1 hora
      **Cobertura temporal**: Janeiro de  2019
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@dados.rio
    columns:
      - name: id_denuncia
        description: "PK | ID único da denúncia no banco de dados."
        data_tests:
          - not_null
          - unique

      - name: numero_denuncia
        description: "Número interno da denúncia gerado pelo sistema."
        data_tests:
          - not_null

      - name: data_denuncia
        description: "Data e hora da denúncia registrada no formato DATETIME GTM-3."
        data_tests:
          - not_null

      - name: data_difusao
        description: "Data e hora da difusão da denúncia registrada no formato DATETIME GTM-3."
        data_tests:
          - not_null

      - name: endereco
        description: "Endereço associado à denúncia."
        data_tests:
          - not_null

      - name: bairro
        description: "Bairro associado à denúncia."
        data_tests:
          - not_null

      - name: municipio
        description: "Município associado à denúncia."
        data_tests:
          - not_null

      - name: estado
        description: "Estado associado à denúncia."
        data_tests:
          - not_null

      - name: latitude
        description: "Latitude do endereço da denúncia."

      - name: longitude
        description: "Longitude do endereço da denúncia."

      - name: relato
        description: "Relato detalhado da denúncia."
        data_tests:
          - not_null

    meta:
      primary_key: id_denuncia