name: 'queries'
version: '1.0.0'
config-version: 2

profile: 'queries'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  +persist_docs:
    relation: true
    columns: true
  queries:
    disque_denuncia:
      +materialized: table
      +schema: disque_denuncia
    integracao_reports:
      +materialized: table
      +schema: integracao_reports
    integracao_reports_staging:
      +materialized: table
      +schema: integracao_reports_staging
    radares_infra:
      +materialized: table
      +schema: radares_infra
    fogo_cruzado:
      +materialized: table
      +schema: fogo_cruzado
    radar_readings:
      +materialized: incremental
      +schema: radar_readings
