queries:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:/temp/EMD/pipelines_rj_civitas/tmp/rj-civitas.json
      location: US
      method: service-account
      priority: interactive
      project: rj-civitas
      threads: 1
      type: bigquery
  target: dev
