queries:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 2
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-civitas-dev
      threads: 8
      type: bigquery
  target: dev

elementary:
  outputs:
    default:
      dataset: "gerenciamento__dbt_elementary"
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-civitas-dev
      threads: 8
      type: "bigquery"