queries:
  outputs:
    dev:
      dataset: disque_denuncia
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /credentials-dev/dev.json
      location: US
      method: service-account
      priority: interactive
      project: rj-civitas-dev
      threads: 1
      type: bigquery

    prod:
      dataset: disque_denuncia
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /credentials-prod/prod.json
      location: US
      method: service-account
      priority: interactive
      project: rj-civitas
      threads: 1
      type: bigquery
  target: dev
