queries:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: datario
      threads: 1
      type: bigquery
  target: dev
