version: 2

sources:
  - name: ocr_radar
    database: rj-cetrio
    schema: ocr_radar
    tables:
      - name: readings_2024
        identifier: readings_2024_*

models:
  - name: previous_next_readings
    description: |
      **Descrição**: Modelo que verifica a leitura anterior e leitura futura para cada leitura do radar.
      **Frequência de Atualização**: Diária.
      **Publicado Por**: |
        Amanda Amaro
      **Publicado Por (email)**: |
        amanda.amaro@prefeitura.rio
    columns:
      - name: camera_numero
        description: "Código do radar."
        tests:
          - not_null

      - name: empresa
        description: "empresa responsável pelo radar."
        tests:
          - not_null

      - name: datahora
        description: "Data e hora da leitura do radar. Substitui data nula pelo timestamp correspondente ao dia."
        tests:
          - not_null

      - name: ultima_leitura_valida
        description: "leitura anterior à leitura do radar."


      - name: proxima_leitura_valida
        description: "leitura posterior à leitura do radar."

