version: 2

sources:
  - name: stg_disque_denuncia
    database: rj-civitas
    schema: disque_denuncia_staging
    tables:
      - name: denuncias
      - name: denuncias_historico
      - name: xpto_denuncia
      - name: xptos
      - name: difusao_externa
      - name: orgaos_externos
      - name: assuntos_denuncias
      - name: assuntos_classes
      - name: assuntos_tipos
      - name: envolvidos
      - name: envolvidos_pele
      - name: envolvidos_estatura
      - name: envolvidos_olhos
      - name: envolvidos_cabelo
      - name: envolvidos_porte

  - name: stg_fogo_cruzado
    database: rj-civitas
    schema: fogo_cruzado_staging
    tables:
      - name: ocorrencias

  - name: stg_integracao_reports
    database: rj-civitas
    schema: integracao_reports_staging
    tables:
      - name: reports_1746
      - name: reports_disque_denuncia
      - name: reports_fogo_cruzado
      - name: reports_telegram
      - name: reports_twitter

  - name: disque_denuncia
    database: rj-civitas
    schema: disque_denuncia
    tables:
      - name: denuncias

  - name: chamados_1746
    database: rj-segovi
    schema: adm_central_atendimento_1746
    tables:
      - name: chamado

  - name: datario
    database: datario
    schema: dados_mestres
    tables:
      - name: logradouro
      - name: bairro

  - name: integracao_reports
    database: rj-civitas
    schema: integracao_reports
    tables:
      - name: tipos_interesse_1746

  - name: ocr_radar
    database: rj-cetrio
    schema: ocr_radar
    tables:
      - name: readings_2024
        identifier: readings_2024_*
      - name: all_readings
        identifier: vw_readings
      - name: all_readings_raw
        identifier: readings_*
      - name: equipamento
      - name: equipamento_codcet_to_camera_numero

  - name: fogo_cruzado
    database: rj-civitas
    schema: fogo_cruzado
    tables:
      - name: ocorrencias

  - name: g20
    database: rj-civitas
    schema: g20
    tables:
      - name: contextos
      - name: reports_enriquecidos
        identifier: reports_enriquecidos_v2

  - name: stg_scraping_redes
    database: rj-civitas
    schema: scraping_redes_staging
    tables:
      - name: telegram_georreferenciado
      - name: telegram_messages
      - name: telegram_chats
      - name: twitter_georreferenciado
      - name: twitter_messages
      - name: twitter_chats

  - name: scraping_redes
    database: rj-civitas
    schema: scraping_redes
    tables:
      - name: telegram
      - name: twitter

  - name: smtr_veiculo
    database: rj-smtr
    schema: veiculo
    tables:
      - name: licenciamento
