version: 2

models:
  - name: denuncias
    description: |
      **Descrição**: Tabela que contém dados de denúncias, incluindo informações de localização e detalhes do relato.
      **Frequência de atualização**: A cada 1 hora
      **Cobertura temporal**: Janeiro de  2019
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@prefeitura.rio
    columns:
      - name: numero_denuncia
        description: "Número interno da denúncia gerado pelo sistema."
        tests:
          - not_null

      - name: id_denuncia
        description: "ID único da denúncia no banco de dados."
        tests:
          - not_null
          - unique

      - name: data_denuncia
        description: "Data e hora da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: data_difusao
        description: "Data e hora da difusão da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: tipo_logradouro
        description: "Tipo do logradouro (rua, avenida, etc.)."

      - name: logradouro
        description: "Nome do logradouro."

      - name: numero_logradouro
        description: "Número do logradouro."

      - name: complemento_logradouro
        description: "Complemento do logradouro (apartamento, bloco, etc.)."

      - name: bairro_logradouro
        description: "Bairro onde está localizado o logradouro."

      - name: subbairro_logradouro
        description: "Subbairro ou região menor dentro do bairro."

      - name: cep_logradouro
        description: "CEP do logradouro."

      - name: referencia_logradouro
        description: "Referência adicional do logradouro."

      - name: municipio
        description: "Município onde está localizado o logradouro."

      - name: estado
        description: "Estado onde está localizado o logradouro."

      - name: latitude
        description: "Latitude da localização da denúncia."

      - name: longitude
        description: "Longitude da localização da denúncia."

      - name: xptos
        description: "Array de informações sobre XPTOs (tags) associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do XPTO."
          - name: nome
            description: "Nome do XPTO."

      - name: orgaos
        description: "Array de órgãos associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do órgão."
          - name: nome
            description: "Nome do órgão."
          - name: tipo
            description: "Tipo do órgão."

      - name: assuntos
        description: "Array de assuntos associados à denúncia."
        subcolumns:
          - name: id_classe
            description: "ID da classe do assunto."
          - name: classe
            description: "Descrição da classe do assunto."
          - name: id_tipo
            description: "ID do tipo de assunto."
          - name: tipo
            description: "Descrição do tipo de assunto."
          - name: assunto_principal
            description: "Indicador do assunto principal."

      - name: relato
        description: "Descrição do relato da denúncia."

      - name: envolvidos
        description: "Array de pessoas envolvidas na denúncia."
        subcolumns:
          - name: id
            description: "Identificador único do registro no banco de dados. NÃO É IDENTIFICADOR ÚNICO PARA O ENVOLVIDO."
          - name: nome
            description: "Nome do envolvido."
          - name: vulgo
            description: "Vulgo do envolvido."
          - name: sexo
            description: "Sexo do envolvido."
          - name: idade
            description: "Idade do envolvido."
          - name: pele
            description: "Descrição da pele do envolvido."
          - name: estatura
            description: "Estatura do envolvido."
          - name: porte
            description: "Porte do envolvido."
          - name: cabelos
            description: "Descrição dos cabelos do envolvido."
          - name: olhos
            description: "Descrição dos olhos do envolvido."
          - name: outras_caracteristicas
            description: "Outras características do envolvido."

      - name: status_denuncia
        description: "Status atual da denúncia."

    meta:
      primary_key: id_denuncia

  - name: denuncias_api
    description: |
      **Descrição**: Tabela que contém dados de denúncias capturadas através da API do Disque Denúncia,
      incluindo informações de localização e detalhes do relato.
      **Frequência de atualização**: A cada 1 hora
      **Cobertura temporal**: 15/07/2024 - hoje (hora - 1)
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@prefeitura.rio
    columns:
      - name: numero_denuncia
        description: "Número interno da denúncia gerado pelo sistema."
        tests:
          - not_null

      - name: id_denuncia
        description: "ID único da denúncia no banco de dados."
        tests:
          - not_null
          - unique

      - name: data_denuncia
        description: "Data e hora da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: data_difusao
        description: "Data e hora da difusão da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: tipo_logradouro
        description: "Tipo do logradouro (rua, avenida, etc.)."

      - name: logradouro
        description: "Nome do logradouro."

      - name: numero_logradouro
        description: "Número do logradouro."

      - name: complemento_logradouro
        description: "Complemento do logradouro (apartamento, bloco, etc.)."

      - name: bairro_logradouro
        description: "Bairro onde está localizado o logradouro."

      - name: subbairro_logradouro
        description: "Subbairro ou região menor dentro do bairro."

      - name: cep_logradouro
        description: "CEP do logradouro."

      - name: referencia_logradouro
        description: "Referência adicional do logradouro."

      - name: municipio
        description: "Município onde está localizado o logradouro."

      - name: estado
        description: "Estado onde está localizado o logradouro."

      - name: latitude
        description: "Latitude da localização da denúncia."

      - name: longitude
        description: "Longitude da localização da denúncia."

      - name: xptos
        description: "Array de informações sobre XPTOs (tags) associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do XPTO."
          - name: nome
            description: "Nome do XPTO."

      - name: orgaos
        description: "Array de órgãos associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do órgão."
          - name: nome
            description: "Nome do órgão."
          - name: tipo
            description: "Tipo do órgão."

      - name: assuntos
        description: "Array de assuntos associados à denúncia."
        subcolumns:
          - name: id_classe
            description: "ID da classe do assunto."
          - name: classe
            description: "Descrição da classe do assunto."
          - name: id_tipo
            description: "ID do tipo de assunto."
          - name: tipo
            description: "Descrição do tipo de assunto."
          - name: assunto_principal
            description: "Indicador do assunto principal."

      - name: relato
        description: "Descrição do relato da denúncia."

      - name: envolvidos
        description: "Array de pessoas envolvidas na denúncia."
        subcolumns:
          - name: id
            description: "Identificador único do registro no banco de dados. NÃO É IDENTIFICADOR ÚNICO PARA O ENVOLVIDO."
          - name: nome
            description: "Nome do envolvido."
          - name: vulgo
            description: "Vulgo do envolvido."
          - name: sexo
            description: "Sexo do envolvido."
          - name: idade
            description: "Idade do envolvido."
          - name: pele
            description: "Descrição da pele do envolvido."
          - name: estatura
            description: "Estatura do envolvido."
          - name: porte
            description: "Porte do envolvido."
          - name: cabelos
            description: "Descrição dos cabelos do envolvido."
          - name: olhos
            description: "Descrição dos olhos do envolvido."
          - name: outras_caracteristicas
            description: "Outras características do envolvido."

      - name: status_denuncia
        description: "Status atual da denúncia."

    meta:
      primary_key: id_denuncia

  - name: denuncias_historico
    description: |
      **Descrição**: Tabela que contém dados históricos de denúncias, incluindo informações de localização e detalhes do relato.
      **Cobertura temporal**: 01/01/2019 - 15/07/2024
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@prefeitura.rio
    columns:
      - name: numero_denuncia
        description: "Número interno da denúncia gerado pelo sistema."
        tests:
          - not_null

      - name: id_denuncia
        description: "ID único da denúncia no banco de dados."
        tests:
          - not_null
          - unique

      - name: data_denuncia
        description: "Data e hora da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: data_difusao
        description: "Data e hora da difusão da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: tipo_logradouro
        description: "Tipo do logradouro (rua, avenida, etc.)."

      - name: logradouro
        description: "Nome do logradouro."

      - name: numero_logradouro
        description: "Número do logradouro."

      - name: complemento_logradouro
        description: "Complemento do logradouro (apartamento, bloco, etc.)."

      - name: bairro_logradouro
        description: "Bairro onde está localizado o logradouro."

      - name: subbairro_logradouro
        description: "Subbairro ou região menor dentro do bairro."

      - name: cep_logradouro
        description: "CEP do logradouro."

      - name: referencia_logradouro
        description: "Referência adicional do logradouro."

      - name: municipio
        description: "Município onde está localizado o logradouro."

      - name: estado
        description: "Estado onde está localizado o logradouro."

      - name: latitude
        description: "Latitude da localização da denúncia."

      - name: longitude
        description: "Longitude da localização da denúncia."

      - name: xptos
        description: "Array de informações sobre XPTOs (tags) associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do XPTO."
          - name: nome
            description: "Nome do XPTO."

      - name: orgaos
        description: "Array de órgãos associados à denúncia."
        subcolumns:
          - name: id
            description: "ID do órgão."
          - name: nome
            description: "Nome do órgão."
          - name: tipo
            description: "Tipo do órgão."

      - name: assuntos
        description: "Array de assuntos associados à denúncia."
        subcolumns:
          - name: id_classe
            description: "ID da classe do assunto."
          - name: classe
            description: "Descrição da classe do assunto."
          - name: id_tipo
            description: "ID do tipo de assunto."
          - name: tipo
            description: "Descrição do tipo de assunto."
          - name: assunto_principal
            description: "Indicador do assunto principal."

      - name: relato
        description: "Descrição do relato da denúncia."

      - name: envolvidos
        description: "Array de pessoas envolvidas na denúncia."
        subcolumns:
          - name: id
            description: "Identificador único do registro no banco de dados. NÃO É IDENTIFICADOR ÚNICO PARA O ENVOLVIDO."
          - name: nome
            description: "Nome do envolvido."
          - name: vulgo
            description: "Vulgo do envolvido."
          - name: sexo
            description: "Sexo do envolvido."
          - name: idade
            description: "Idade do envolvido."
          - name: pele
            description: "Descrição da pele do envolvido."
          - name: estatura
            description: "Estatura do envolvido."
          - name: porte
            description: "Porte do envolvido."
          - name: cabelos
            description: "Descrição dos cabelos do envolvido."
          - name: olhos
            description: "Descrição dos olhos do envolvido."
          - name: outras_caracteristicas
            description: "Outras características do envolvido."

      - name: status_denuncia
        description: "Status atual da denúncia."

    meta:
      primary_key: id_denuncia
