version: 2

models:
  - name: denuncias
    description: |
      **Descrição**: Tabela que contém dados de denúncias, incluindo informações de localização e detalhes do relato.
      **Frequência de atualização**: A cada minuto
      **Cobertura temporal**: Janeiro de  2019
      **Publicado por**: Nicolas Evilasio
      **Publicado por (email)**: nicolas.evilasio@prefeitura.rio
    columns:
      - name: numero_denuncia
        description: "Número interno da denúncia gerado pelo sistema."
        tests:
          - not_null

      - name: id_denuncia
        description: "ID único da denúncia no banco de dados."
        tests:
          - not_null
          - unique

      - name: data_denuncia
        description: "Data e hora da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: data_difusao
        description: "Data e hora da difusão da denúncia registrada no formato DATETIME GTM-3."
        tests:
          - not_null

      - name: tipo_logradouro
        description: "Tipo do logradouro (rua, avenida, etc.)."

      - name: logradouro
        description: "Nome do logradouro."

      - name: numero_logradouro
        description: "Número do logradouro."

      - name: complemento_logradouro
        description: "Complemento do logradouro (apartamento, bloco, etc.)."

      - name: bairro_logradouro
        description: "Bairro onde está localizado o logradouro."

      - name: subbairro_logradouro
        description: "Subbairro ou região menor dentro do bairro."

      - name: cep_logradouro
        description: "CEP do logradouro."

      - name: referencia_logradouro
        description: "Referência adicional do logradouro."

      - name: municipio
        description: "Município onde está localizado o logradouro."

      - name: estado
        description: "Estado onde está localizado o logradouro."

      - name: latitude
        description: "Latitude da localização da denúncia."

      - name: longitude
        description: "Longitude da localização da denúncia."

      - name: xptos
        description: "Array de informações sobre XPTOs (tags) associados à denúncia."

      - name: xptos.id
        description: "ID do XPTO."

      - name: xptos.nome
        description: "Nome do XPTO."

      - name: orgaos
        description: "Array de órgãos associados à denúncia."

      - name: orgaos.id
        description: "ID do órgão."

      - name: orgaos.nome
        description: "Nome do órgão."

      - name: orgaos.tipo
        description: "Tipo do órgão."

      - name: assuntos
        description: "Array de assuntos associados à denúncia."

      - name: assuntos.id_classe
        description: "ID da classe do assunto."

      - name: assuntos.classe
        description: "Descrição da classe do assunto."

      - name: assuntos.tipos
        description: "Array de tipos associados à classe da denúncia."

      - name: assuntos.tipos.id_tipo
        description: "ID do tipo de assunto."

      - name: assuntos.tipos.tipo
        description: "Descrição do tipo de assunto."

      - name: assuntos.tipos.assunto_principal
        description: "Indicador do assunto principal."

      - name: relato
        description: "Descrição do relato da denúncia."

      - name: envolvidos
        description: "Array de pessoas envolvidas na denúncia."

      - name: envolvidos.id
        description: "Identificador único do registro no banco de dados. NÃO É IDENTIFICADOR ÚNICO PARA O ENVOLVIDO."

      - name: envolvidos.nome
        description: "Nome do envolvido."

      - name: envolvidos.vulgo
        description: "Vulgo do envolvido."

      - name: envolvidos.sexo
        description: "Sexo do envolvido."

      - name: envolvidos.idade
        description: "Idade do envolvido."

      - name: envolvidos.pele
        description: "Descrição da pele do envolvido."

      - name: envolvidos.estatura
        description: "Estatura do envolvido."

      - name: envolvidos.porte
        description: "Porte do envolvido."

      - name: envolvidos.cabelos
        description: "Cor dos cabelos do envolvido."

      - name: envolvidos.olhos
        description: "Cor dos olhos do envolvido."

      - name: envolvidos.outras_caracteristicas
        description: "Outras características do envolvido."

      - name: status_denuncia
        description: "Status atual da denúncia."

      - name: timestamp_insercao
        description: "Timestamp da inserção do registro no banco de dados."

    meta:
      primary_key: id_denuncia
