version: 2

sources:
  - name: disque_denuncia
    database: rj-civitas
    schema: disque_denuncia
    tables:
      - name: denuncias

  - name: chamados_1746
    database: rj-segovi
    schema: adm_central_atendimento_1746
    tables:
      - name: chamado

  - name: datario
    database: datario
    schema: dados_mestres
    tables:
      - name: logradouro

  - name: integracao_reports
    database: rj-civitas
    schema: integracao_reports
    tables:
      - name: tipos_interesse_1746
